require("prototypes.autoplace-controls")
require("prototypes.category")
require("prototypes.entity")
require("prototypes.item")
require("prototypes.noise-layers")
require("prototypes.recipe")
require("prototypes.resources")